apps:
  - name: "Basecamp"
    app_category: "Project Management"
    ios_url: "https://apps.apple.com/us/app/basecamp-project-management/id1015603248"
    android_url: "https://play.google.com/store/apps/details?id=com.basecamp.bc3&hl=en_US&gl=US&pli=1"
    web_url: "https://basecamp.com"
    image: "basecamp.webp"

  - name: "Hey"
    app_category: "Email"
    ios_url: "https://apps.apple.com/us/app/hey-email/id1506603805"
    android_url: "https://play.google.com/store/apps/details?id=com.basecamp.hey"
    web_url: "https://www.hey.com"
    image: "hey.webp"

  - name: "RailsDevs"
    app_category: "Developer Tools"
    ios_url: "https://apps.apple.com/us/app/railsdevs/id1621607837"
    web_url: "https://railsdevs.com"
    image: "railsdevs.webp"

  - name: "Context Travel"
    app_category: "Travel"
    ios_url: "https://apps.apple.com/ca/app/context-travel/id1630419856"
    web_url: "https://www.contexttravel.com"
    image: "context_travel.webp"

  - name: "BeerMenus"
    app_category: "Food & Drink"
    ios_url: "https://apps.apple.com/app/apple-store/id917882057"
    web_url: "https://www.beermenus.com"
    image: "beermenus.webp"

  - name: "PieHoled"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/us/app/pieholed/id6467455236"
    web_url: "https://pieholedapp.com"
    image: "pieholed.webp"

  - name: "Hauling Buddies"
    app_category: "Business"
    android_url: "https://play.google.com/store/apps/details?id=com.haulingbuddies.android"
    web_url: "https://haulingbuddies.com"
    image: "hauling_buddies.webp"

  - name: "Hoist"
    app_category: "Business"
    ios_url: "https://apps.apple.com/us/app/hoist-up/id1592340401"
    image: "hoist.webp"

  - name: "GolfSheet"
    app_category: "Sports"
    ios_url: "https://apps.apple.com/us/app/golf-leaguer/id1627580628"
    image: "golfsheet.webp"

  - name: "OM App: Partnered Meditation"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/app/apple-store/id1635491251"
    web_url: "https://instituteofom.com"
    image: "om.webp"

  - name: "MxU"
    app_category: "Education"
    ios_url: "https://apps.apple.com/us/app/mxu/id6448795537"
    web_url: "https://getmxu.com"
    image: "mxu.webp"

  - name: "Amba - Health and Wellbeing"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/us/app/amba-health-and-wellbeing/id1565130657"
    web_url: "https://www.amba.co"
    image: "amba.webp"

  - name: "PlanGo - for Instructors"
    app_category: "Business"
    ios_url: "https://apps.apple.com/nl/app/plango-instructeursapp/id1096866451"
    android_url: "https://play.google.com/store/apps/details?id=nl.plango.instructeurs"
    image: "plango_instructors.webp"

  - name: "PlanGo - for Students"
    app_category: "Education"
    ios_url: "https://apps.apple.com/nl/app/plango-leerlingapp/id1140253719"
    android_url: "https://play.google.com/store/apps/details?id=nl.plango.leerlingen"
    image: "plango_students.webp"

  - name: "Robodash"
    app_category: "Developer Tools"
    ios_url: "https://apps.apple.com/us/app/robodash/id1522653081"
    image: "robodash.webp"

  - name: "RockLife"
    app_category: "Education"
    ios_url: "https://apps.apple.com/mx/app/rocklife/id1621826773"
    android_url: "https://play.google.com/store/apps/details?id=com.rocklife.app"
    image: "rocklife.webp"

  - name: "Smart Strength"
    app_category: "Health & Fitness"
    ios_url: "https://apps.apple.com/ie/app/smart-strength/id1600256651"
    image: "smartstrength.webp"

  - name: "Heatspring"
    app_category: "Education"
    ios_url: "https://apps.apple.com/us/app/heatspring-online-courses/id6449776941"
    image: "heatspring.webp"

  - name: "Enjoy Kitchen"
    app_category: "Food & Drink"
    ios_url: "https://apps.apple.com/mx/app/enjoy-kitchen/id6443742018"
    android_url: "https://play.google.com/store/apps/details?id=mx.enjoykitchen.shop"
    web_url: "https://enjoykitchen.mx"
    image: "enjoy_kitchen.webp"

  - name: "myRent"
    app_category: "Real Estate"
    ios_url: "https://apps.apple.com/us/app/myrent/id6447619622"
    android_url: "https://play.google.com/store/apps/details?id=nz.co.myrent.myRent"
    image: "myrent.webp"

  - name: "Plant Journal - Ploi"
    app_category: "Lifestyle"
    ios_url: "https://apps.apple.com/app/apple-store/id1624280409?pt=124998291&ct=tnd&mt=8"
    android_url: "https://play.google.com/store/apps/details?id=com.devjah.plants"
    image: "ploi.webp"
